[general]
default_module = "ddg"
empty_module = "app"
exec_cmd = "zsh -c"
esc_to_abort = true
cheatsheet_entry = "?"
cheatsheet_viewer = "less -R; clear"

[interface]
a = 1
place_holder = "type and search"
hint_mode = "hint"

[[modules]]
description = "search with duckduckgo"
prefix = "ddg"
cmd = "xdg-open 'https://duckduckgo.com/?q={}'"
with_arguments = true
url_encode = true

[[modules]]
description = "launch an app"
prefix = "app"
cmd = """
desktop_files() {
    setopt localoptions sh_word_split
    local IFS=":"
    for data_dir in $XDG_DATA_DIRS; do
        find $data_dir/applications -name "*.desktop"
    done
}
desktop_files | fzf
"""
